### ISSUE TITLE
Omeka S Encountered an Error after submitting

### ISSUE THREAD

**Issue by danielebrox** [Daniel-KM/Omeka-S-module-CustomOntology#1]
Hello Daniel,
congratulation for this very useful module.
When I compile the ontology form and click on "Submit" I've got the error "Omeka S encountered an error". 
I followed all the instructions and installed the module on Omeka S 1.0.1. I have also modified CustomOntologyController.php (even if it is not related I think).
I think I have properly used the required syntax, because when I submit with a wrong syntax I got errors on screen like "Label missing".
Here what I write:
Namespace uri: http://c43961.sgvps.net/~dani2020/omeka-s/ns/parkandgarden#
Prefix: parkandgarden
Label: Park and Garden
Comment: Park and garden ontology
Classes:
parkandgarden:Site,Site,A site of a park or a garden
Properties:
parkandgarden:sourceReference,Source Reference
parkandgarden:masterOrComponent,Master or Component
parkandgarden:currentUse,Current use

I tried to add the second comma at the end of the lines, but I got the same error.
Any idea?

**Comment by Daniel-KM** [comment]
Thanks for trying this new module!
Can you retry with the current master version? I may have fix your error since.

**Comment by danielebrox** [comment]
Yes indeed.
You have already solved it in the new master.
Thank you very much, everything is working now!
Best.
