### ISSUE TITLE
Omeka version error

### ISSUE THREAD

**Issue by JohnMulligan** [Daniel-KM/Omeka-S-module-CustomOntology#3]
Hi Daniel,

Omeka gives me an error when I try to install this, that "Error: Custom Ontology requires Omeka S ^1.0.0 || ^2.0.0"

Composer works fine off the command line. Do you have a fix for this/have you encountered this error before? It's an incredibly useful module, I'm using it for just about all my installations :)

Thanks!

John

**Comment by Daniel-KM** [comment]
It is probably fixed with the new version for Omeka 3.

**Comment by JohnMulligan** [comment]
Can confirm, it works on the new version!
